In [6]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import importlib
import os
import sys

from base.experiment import *
from logistic.env_logistic import *
from logistic.agent_logistic import *
from utils import *
from compare_utils import *
from agents import *

import copy
import numpy as np
import math
import matplotlib.pyplot as plt
import numpy.linalg as npla
import scipy.linalg as spla
import pickle
import pandas as pd
import plotnine as gg
import warnings
warnings.filterwarnings('ignore')


#https://www.tutorialspoint.com/python/python_command_line_arguments.htm
#print 'Number of arguments:', len(sys.argv), 'arguments.'
#print 'Argument List:', str(sys.argv)
time=0.1
T=1000
name='../outputs/ma/wc'
seed=201
num_articles = 100
dim = 20
dim1 = dim+1
sparsity = 5.0
verbosity=1
batch_size = 64
agents = make_shortlist_agents(num_articles, dim, sparsity, time, verbosity=verbosity, batch_size=batch_size)
mala_agent = MalaTS(num_articles, dim1, [0]*dim1, cov=None, 
                                             step_size=lambda t: 0.5/(1 + t * np.sqrt(sparsity/dim)), time=time, n_steps=9999,
                                             init_pt=None, verbosity=verbosity, leapfrog = True)
"""['mala_lf',
                    'online_laplace',
                    'pg',
                    'sgld',
                    'sagald',
                    'prec_sagald']"""
agents = [mala_agent]+agents
results = simple_compare(agents, num_articles, dim, sparsity, T, seed, verbosity=1, force=True)
agents_info = [agents[0].theta,
               (agents[1].est_coeffs, agents[1].est_inv_vars),
               agents[3].theta,
               (agents[4].theta, agents[4].gradient, agents[4].gradients),
               (agents[5].theta, agents[5].gradient, agents[5].gradients, agents[5].weights)]
pickle.dump(agents_info, open('%s_agents.p' % name,'wb'))
data = (agents[0].contexts,agents[0].rewards)
pickle.dump(data, open('%s_data.p' % name,'wb'))        
samples_list = []
agent0 = copy.deepcopy(agents[0])
agent0.v=1
agent0.time=0
agent0.n_steps=1000
agents = [agent0] + agents
for agent in agents:
    samples = redraw_samples(agent, 1000, 2)
    samples_list += [samples]
samples_list = np.asarray(samples_list)
pickle.dump(samples_list, open('%s.p' % name,'wb'))
print(merr(samples_list, 0.25))

# '../outputs/ma1.p'

theta [ 0.31678346 -0.4934171   1.21794581  0.43677076 -0.72769267  0.43030744
 -0.68666532 -0.45301801 -0.73285921 -0.75362743 -0.83251892  0.44987187
  1.80752304 -0.48953136  0.88158874 -0.69834087 -0.0499747   1.90752236
 -0.32762267  1.15003185 -0.44868018]
Experiment: Step 0
 Accept proportion: 0.438320
 Steps taken: 381
 Cum regret: 0.750294
 Cum regret: 0.750294
 Cum regret: 0.750294
 Steps taken: 0
 Cum regret: 0.750294
 Steps taken: 0
 Cum regret: 0.750294
 Steps taken: 0
 Cum regret: 0.750294
Experiment: Step 1
 Accept proportion: 0.717742
 Steps taken: 248
 Cum regret: 1.124801
 Cum regret: 1.124801
 Steps taken: 258
 Cum regret: 1.124801
 Steps taken: 890
 Cum regret: 1.124801
 Steps taken: 1008
 Cum regret: 1.124801
 Steps taken: 99
 Cum regret: 1.124801
Experiment: Step 2
 Accept proportion: 0.713656
 Steps taken: 227
 Cum regret: 1.642661
 Cum regret: 1.642661
 Steps taken: 240
 Cum regret: 1.642661
 Steps taken: 1077
 Cum regret: 1.642661
 Steps taken: 1228
 Cum regret

 Steps taken: 947
 Cum regret: 9.209277
 Steps taken: 1107
 Cum regret: 9.209277
 Steps taken: 163
 Cum regret: 9.209277
Experiment: Step 30
 Accept proportion: 0.940000
 Steps taken: 300
 Cum regret: 9.603498
 Cum regret: 9.603498
 Steps taken: 320
 Cum regret: 9.603498
 Steps taken: 955
 Cum regret: 9.603498
 Steps taken: 1098
 Cum regret: 9.603498
 Steps taken: 122
 Cum regret: 9.603498
Experiment: Step 31
 Accept proportion: 0.901042
 Steps taken: 192
 Cum regret: 9.978758
 Cum regret: 9.978758
 Steps taken: 242
 Cum regret: 9.978758
 Steps taken: 668
 Cum regret: 9.978758
 Steps taken: 775
 Cum regret: 9.978758
 Steps taken: 110
 Cum regret: 9.978758
Experiment: Step 32
 Accept proportion: 0.965174
 Steps taken: 201
 Cum regret: 10.172605
 Cum regret: 10.172605
 Steps taken: 165
 Cum regret: 10.172605
 Steps taken: 631
 Cum regret: 10.172605
 Steps taken: 1078
 Cum regret: 10.172605
 Steps taken: 126
 Cum regret: 10.172605
Experiment: Step 33
 Accept proportion: 0.952862
 Steps ta

KeyboardInterrupt: 

In [ ]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import importlib
import os
import sys

from base.experiment import *
from logistic.env_logistic import *
from logistic.agent_logistic import *
from utils import *
from compare_utils import *
from agents import *

import copy
import numpy as np
import math
import matplotlib.pyplot as plt
import numpy.linalg as npla
import scipy.linalg as spla
import pickle
import pandas as pd
import plotnine as gg
import warnings
warnings.filterwarnings('ignore')


#https://www.tutorialspoint.com/python/python_command_line_arguments.htm
#print 'Number of arguments:', len(sys.argv), 'arguments.'
#print 'Argument List:', str(sys.argv)
time=0.1
T=1000
name='../outputs/ma/wc'
seed=201
num_articles = 100
dim = 20
dim1 = dim+1
sparsity = 5.0
verbosity=1
batch_size = 64
agents = make_shortlist_agents(num_articles, dim, sparsity, time, verbosity=verbosity, batch_size=batch_size)
mala_agent = MalaTS(num_articles, dim1, [0]*dim1, cov=None, 
                                             step_size=lambda t: 0.5/(1 + t * np.sqrt(sparsity/dim)), time=time, n_steps=9999,
                                             init_pt=None, verbosity=verbosity, leapfrog = True)
"""['mala_lf',
                    'online_laplace',
                    'pg',
                    'sgld',
                    'sagald',
                    'prec_sagald']"""
agents = [mala_agent]+agents
#results = simple_compare(agents, num_articles, dim, sparsity, T, seed, verbosity=1, force=True)
[agents[0].theta,
               (agents[1].est_coeffs, agents[1].est_inv_vars),
               agents[3].theta,
               (agents[4].theta, agents[4].gradient, agents[4].gradients),
               (agents[5].theta, agents[5].gradient, agents[5].gradients, agents[5].weights)] =\
                    pickle.load(open('%s_agents.p' % name,'rb'))
(contexts, rewards) = pickle.load(open('%s_data.p' % name,'rb'))        
for i in range(6):
    (agents[i].contexts,agents[i].rewards) = (contexts, rewards)
samples_list = []
agent0 = copy.deepcopy(agents[0])
agent0.v=1
agent0.time=0
agent0.n_steps=1000
agents = [agent0] + agents[1:]
i=0
for agent in agents:
    agent.num_plays = T
    samples = redraw_samples(agent, 1000, 2)
    samples_list += [samples]
    pickle.dump(samples, open('%s_%d.p' % (name,i),'wb'))
    i+=1
samples_list = np.asarray(samples_list)
pickle.dump(samples_list, open('%s.p' % name,'wb'))
print(merr(samples_list, 0.25))

# '../outputs/ma1.p'

Drawing sample 1
 Accept proportion: 0.985000
 Steps taken: 1000
 array([ 0.56692048, -0.55681608,  1.65535983,  0.56130372,  0.36799988,
        0.61579732, -1.33793669, -0.55422431, -0.54015563, -1.53080162,
       -0.42916106, -0.54848565,  2.21673086, -0.54479742,  0.78959946,
       -0.38118283,  0.01811719,  0.22434081, -1.41743071,  1.12305144,
        0.60657409])
Drawing sample 2
 Accept proportion: 0.988000
 Steps taken: 1000
 array([ 1.72542251, -1.00487875,  0.7530434 ,  0.91320717, -0.17187462,
        0.28113779, -1.66936062, -0.78006007,  0.07762304, -0.66647754,
       -0.00577105, -0.42902713,  1.5833744 , -0.65227539,  0.4434619 ,
       -0.04648531, -0.38308515,  1.15084835, -0.7334021 ,  0.63796445,
       -0.13905998])
Drawing sample 3
 Accept proportion: 0.983000
 Steps taken: 1000
 array([-0.70155729, -0.61877531,  0.49923418,  1.68604474, -0.83172353,
        1.29391156, -1.14084692,  0.09912703, -0.54273345, -1.03830234,
        0.41429811,  0.02387425,  2.0250

 Accept proportion: 0.987000
 Steps taken: 1000
 array([-2.27660214e-01, -8.39632017e-01,  7.06237024e-01,  5.60223500e-01,
       -2.99419302e-01,  1.01580820e+00, -1.33827040e+00, -1.07755899e-01,
       -4.23886928e-01, -9.32229464e-01, -2.19528327e-02, -1.85157531e-03,
        1.98846734e+00,  1.08723810e-01,  1.17726394e+00, -5.46255828e-01,
       -2.11392624e-01,  1.64016335e+00, -4.19677737e-01,  9.10904931e-01,
        1.71728839e-01])
Drawing sample 24
 Accept proportion: 0.995000
 Steps taken: 1000
 array([-3.35346854e-01, -1.01254196e+00,  8.70794475e-01,  8.10068746e-01,
       -5.36720355e-01,  1.11818687e+00, -9.61975689e-04, -8.95589324e-01,
       -2.94596581e-01, -4.87254580e-01, -2.08786112e-01, -8.01645882e-01,
        2.31152127e+00, -2.10869601e-01,  1.09157478e+00, -2.11184297e-01,
        2.52632107e-01,  1.39577045e+00, -8.96839481e-01,  1.05426107e+00,
        7.32514229e-01])
Drawing sample 25
 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.5068226

 Accept proportion: 0.987000
 Steps taken: 1000
 array([-0.45740131, -0.74137519,  0.27368585,  1.71541554,  0.47148369,
        1.55559397, -0.77076127, -0.39701682, -0.15996428, -0.95591161,
        0.40955528, -0.56279011,  2.65312707,  0.05607264,  0.54042569,
        0.19225239, -0.03182589,  0.76365293, -1.34600532,  1.19028136,
       -0.26476726])
Drawing sample 46
 Accept proportion: 0.982000
 Steps taken: 1000
 array([-0.13613314, -0.71355599,  1.27843061,  0.45375625,  0.46858653,
        0.88945233, -1.13471547, -0.49335697, -0.53272558, -1.09564328,
       -0.27044463, -0.40717268,  1.78977117,  0.14282299,  0.49549034,
       -0.10484426, -0.0724182 ,  1.23449213, -1.06592761,  1.0814909 ,
        0.64794803])
Drawing sample 47
 Accept proportion: 0.995000
 Steps taken: 1000
 array([ 0.82243527, -0.73294407,  0.22650097,  0.91707148,  0.09612481,
        0.37498189, -0.7491282 , -0.4631765 , -0.90259647, -0.72953723,
        0.08687423, -0.45631409,  1.36846411, -0.091616

 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.32124594, -1.34815213,  0.93960205,  1.6326984 ,  0.03699535,
        0.27679516, -1.44372955, -0.39953195,  0.00895334, -0.93923758,
       -0.1604312 , -0.66461294,  2.26916501, -0.63119861,  0.47003724,
       -0.15282824,  0.1453925 ,  1.23903894, -0.53077947,  0.87785828,
        0.22055088])
Drawing sample 68
 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 0.5362202 , -0.82252137,  0.89276598,  0.39611925, -1.16926598,
        0.3951393 , -0.86107205, -0.5063571 , -0.31586596, -0.93380695,
       -0.03582816, -0.97317553,  1.93718801, -0.0476119 ,  0.45878666,
       -0.45352196,  0.43666025,  1.627677  , -0.5837519 ,  1.08747237,
        0.02929723])
Drawing sample 69
 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 1.30149044e-01, -8.55955534e-01,  1.07879985e+00,  5.94338514e-01,
       -4.29721474e-01,  4.43671182e-01, -7.90147093e-01,  1.29617218e-03,
       -3.17035547e-01, -6.78621545e-01, -4.23865

 Accept proportion: 0.994000
 Steps taken: 1000
 array([ 0.45117444, -0.31489264,  1.07264281,  0.58512314,  0.08683954,
        0.86007642, -1.14917971, -0.48489306, -0.55975328, -0.29441817,
       -0.14222594, -0.37252201,  1.5909918 ,  0.25007326,  0.88243708,
       -0.95234167, -0.08467375,  1.12802828, -0.29272224,  0.77778509,
        0.08282998])
Drawing sample 90
 Accept proportion: 0.983000
 Steps taken: 1000
 array([-0.21802627, -0.50432655,  1.00343608,  1.03502059, -0.49012643,
        1.28595988,  0.1603814 , -0.20408727, -0.27178478, -0.97003131,
       -0.42303943, -0.4391508 ,  1.95899246, -0.5038851 ,  0.08224678,
       -0.39930619,  0.01398195,  1.96649056, -1.43016716,  0.7235359 ,
        0.08012999])
Drawing sample 91
 Accept proportion: 0.989000
 Steps taken: 1000
 array([-0.05070703, -0.64265458,  1.33316736,  0.771433  , -0.53821713,
        0.33284271, -1.05609727, -0.04270924, -0.59194641, -0.90755445,
        0.25642697,  0.23732521,  2.39005597,  0.086559

 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.76929093, -0.7467117 ,  1.41778164,  0.58801674, -0.65229135,
        0.51324525, -1.38561458, -0.35923108, -0.05572698, -0.58602913,
       -0.14245975,  0.18314462,  1.45987111, -0.85378015,  1.04564739,
       -0.63172649, -0.12297321,  1.02661658, -1.27312977,  0.68293332,
       -0.06888613])
Drawing sample 112
 Accept proportion: 0.987000
 Steps taken: 1000
 array([-0.11284388, -0.90984901,  1.00251006,  0.72716671, -0.43133694,
        0.83687565, -1.2204152 , -0.3644427 , -0.14350253, -0.79655823,
        0.1700693 ,  0.0302289 ,  1.69348942, -0.53321038,  0.93992656,
       -0.48120107,  0.45411093,  1.08634118, -1.00344175,  1.11670598,
        0.46490805])
Drawing sample 113
 Accept proportion: 0.988000
 Steps taken: 1000
 array([ 0.05122862,  0.28325986,  0.97461315,  0.76751389, -0.83892489,
        0.17981468, -0.86281182, -0.38324879, -0.30285064, -1.54875055,
        0.04689011, -0.90819861,  2.28569952, -0.4377

 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.31257212, -1.35175474,  1.3329698 ,  1.38788688, -0.119514  ,
        0.48648897, -1.5128203 , -0.09324361, -0.67528359, -1.04089492,
       -0.81031421, -0.0369904 ,  1.72940242,  0.11513057,  0.76881659,
       -0.89375349,  0.06457231,  1.51112897, -1.25414008,  1.1735247 ,
        0.15694666])
Drawing sample 134
 Accept proportion: 0.991000
 Steps taken: 1000
 array([ 1.16347715, -0.27484618,  0.62896176,  0.13696996, -0.27786869,
        0.90409177, -1.41593199,  0.08592555, -0.44271569, -0.88114614,
       -0.27319456,  0.46296885,  1.72101112, -0.43726451,  0.53321653,
       -1.49442035, -0.01425472,  0.94354802, -0.85317685,  0.3683464 ,
       -0.17308813])
Drawing sample 135
 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.95542659, -0.69844079,  0.73558007,  0.82735323,  0.25001435,
        0.2010316 , -0.5689869 , -0.22589378, -0.68775011, -0.66811288,
        0.28916324, -0.11842583,  1.83608523,  0.3011

 Accept proportion: 0.986000
 Steps taken: 1000
 array([-0.13007089, -0.83007795,  0.91167548,  0.66794396, -0.56064502,
        0.94821491, -1.2853594 ,  0.63416462, -0.26744013, -1.00144485,
       -0.29105627, -0.17510151,  1.92025997, -0.42628023,  0.51471276,
       -0.66139874,  0.24068023,  1.00831325, -1.10690969,  1.3228111 ,
        0.17932205])
Drawing sample 156
 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.95930145, -1.04907272,  0.64993768,  1.13061475, -0.54767049,
        0.51582736, -0.68228877, -0.38129816, -0.02516577, -0.70354749,
       -0.29866102, -0.21732396,  1.82276281, -0.45883729,  0.52145025,
       -0.51420888, -0.43417716,  1.029081  , -0.63086405,  0.63786141,
       -0.00377379])
Drawing sample 157
 Accept proportion: 0.995000
 Steps taken: 1000
 array([ 0.74423702, -1.23562764,  0.85109364,  0.70004688, -0.54609016,
        0.57462506, -0.63508633, -0.37517035, -1.09548432, -1.13581938,
        0.08415284, -0.54823941,  2.24278087, -0.4329

 Accept proportion: 0.982000
 Steps taken: 1000
 array([ 0.68963209, -0.78753811,  0.74170279,  1.10721197, -0.83825303,
        0.05451051, -0.49621179, -0.00236241, -0.34812984, -1.34503289,
        0.02815603, -0.55292337,  1.92832119,  0.13813919,  0.94767044,
       -1.26508264, -0.05588601,  1.01442207, -0.19502049,  1.38853617,
       -0.30113926])
Drawing sample 178
 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 0.46099528, -1.35844606,  0.98883008,  1.39299272,  0.00794674,
        1.21502529, -0.44339574, -0.90044073,  0.42562181, -1.17902252,
       -0.81302805, -0.05159877,  1.55656338, -0.39745612,  0.34332842,
       -0.49039892, -0.27315261,  1.4928922 , -0.94049903,  0.81079706,
        0.32568306])
Drawing sample 179
 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 0.03811655, -0.51028635,  1.11524656,  1.10034106, -0.09018339,
        0.49215699, -0.40115228, -0.68919254, -1.62435061, -1.00072404,
       -0.02280376, -0.34484405,  2.5185282 ,  0.1063

 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.34910354, -0.77278725,  0.71897877,  0.62720783, -1.17355132,
        0.83780515, -0.37087695,  0.41907522,  0.11018265, -1.05315334,
        0.38563077, -0.60657235,  2.06019849, -0.37006399,  0.54278187,
       -0.42631048,  0.43408682,  1.27278063, -0.88406115,  0.82488554,
       -0.29636828])
Drawing sample 200
 Accept proportion: 0.988000
 Steps taken: 1000
 array([ 1.13603425, -1.49218104,  1.32343037,  0.72158601,  0.0260849 ,
        0.57247185, -0.47199765,  0.06133594, -0.46618903, -1.08683426,
       -0.33690186, -0.32524472,  1.38725702, -0.71550161,  0.54835015,
       -0.52258944,  0.1921986 ,  0.57982256, -0.55143981,  0.68641122,
       -0.06878678])
Drawing sample 201
 Accept proportion: 0.990000
 Steps taken: 1000
 array([-0.16288563, -0.45285383,  0.73609771,  0.59079363, -0.70160782,
        0.86808332,  0.04057717,  0.30183945, -0.20299221, -1.34674543,
       -0.14480233, -0.36827831,  1.67742702,  0.0928

 Accept proportion: 0.993000
 Steps taken: 1000
 array([ 0.33744506, -1.09867388,  0.80074725,  0.24110258, -0.44097934,
        0.67845198, -1.3325522 , -0.33622545, -0.1871237 , -1.00958556,
       -0.43672758, -0.06424327,  1.44665296,  0.24977258,  0.95108957,
       -1.07977887,  0.2892604 ,  1.44986215, -0.86697094,  1.31037181,
        0.59251713])
Drawing sample 222
 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.49801283, -1.46791309,  1.15227844,  0.61388164, -0.50909197,
        0.93902823, -0.84816702, -0.53644641, -0.72052008, -0.72306983,
        0.02899807, -0.33850499,  1.82493309, -0.48229148,  0.8665895 ,
        0.01685231,  0.08188579,  1.67356515, -1.96030609,  0.94180454,
       -0.22490584])
Drawing sample 223
 Accept proportion: 0.991000
 Steps taken: 1000
 array([-0.07331206, -0.40471527,  1.01768706,  1.10760148, -0.43995433,
        1.12339112, -0.07278798,  0.02736494, -0.08887085, -1.50037172,
        0.56318195, -0.46265093,  1.89028112,  0.1995

 Accept proportion: 0.992000
 Steps taken: 1000
 array([-0.83170022, -0.16561352,  0.62890536, -0.1304307 , -0.34384775,
        0.91502924, -0.73280134, -0.0106365 , -0.21048546, -0.92990702,
        0.13668007,  0.00514963,  2.66167711, -0.34058906,  1.43547445,
       -0.96940196,  0.24147822,  1.81061472, -0.35721382,  0.85437383,
        0.02616969])
Drawing sample 244
 Accept proportion: 0.993000
 Steps taken: 1000
 array([ 0.74009105, -0.85618011,  0.32050108,  0.34313573,  0.23055358,
        1.02898586, -0.34207248, -0.51254252, -1.08615323, -1.5263882 ,
       -0.00285327,  0.05342676,  1.9503789 ,  0.00469423,  1.19262044,
       -0.51449123, -0.0420224 ,  0.90661871,  0.00619518,  0.77168006,
       -0.11877225])
Drawing sample 245
 Accept proportion: 0.995000
 Steps taken: 1000
 array([ 0.37107862, -1.05543601,  1.07974897,  1.06592567, -0.5060358 ,
       -0.05303644,  0.27775915,  0.04257484, -0.99334656, -0.54151871,
        0.1768239 , -0.63316675,  2.07650648,  0.7678

 Accept proportion: 0.986000
 Steps taken: 1000
 array([ 0.73347418, -1.31914276,  0.31925905,  0.62643067, -0.17447948,
        1.04029287,  0.13295668,  0.20167047, -0.40787279, -0.94531695,
       -0.66975827, -0.66750223,  1.98389421, -0.37848804,  1.04958674,
       -0.32247167,  0.22946465,  0.79110403, -0.20353083,  0.83266075,
       -0.36077588])
Drawing sample 266
 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 0.86716281, -0.72147948,  0.75562276,  0.89206527, -0.12051493,
        0.91708706, -0.86503421, -0.47430336, -0.16623463, -1.11188935,
        0.00892088, -0.60754686,  1.66074416, -0.90666584,  0.65601957,
       -0.18529916,  0.06479882,  1.03840234, -1.1307105 ,  1.22918865,
       -0.31870808])
Drawing sample 267
 Accept proportion: 0.992000
 Steps taken: 1000
 array([-0.25179233, -0.32722804,  1.13407615,  1.2330677 ,  0.11982279,
        0.96257966, -0.6850942 , -0.29088402, -0.52818355, -1.41445387,
       -0.8613551 , -0.32527594,  1.89468657,  0.1993

 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.00682558, -1.17143381,  1.17855317,  0.72986456, -0.39187807,
        0.77316923, -0.60597773, -0.82578676,  0.26855014, -1.68987446,
        0.36445673, -0.29970215,  2.06670588, -0.03819467,  1.03084385,
       -0.85716153, -0.49085181,  1.18544623, -0.8399647 ,  1.17214356,
        0.50824352])
Drawing sample 288
 Accept proportion: 0.987000
 Steps taken: 1000
 array([-0.27833591, -1.20417111,  1.48927343,  1.2370688 , -0.33996974,
        0.47673874, -0.66459619, -0.85815675, -1.03973354, -1.83424145,
       -0.32049377, -0.20167032,  2.55899647, -0.95054623,  0.74259074,
       -0.99752335,  0.29648291,  1.69067761, -1.47497493,  1.07081795,
        0.40794663])
Drawing sample 289
 Accept proportion: 0.993000
 Steps taken: 1000
 array([ 0.47976298, -0.31685925,  0.84757196,  0.30859062,  0.01669649,
        0.71166763, -1.55957581, -0.84983215, -0.0465865 , -0.90601399,
       -0.23733691,  0.1494753 ,  1.69089199, -0.4808

 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 0.1763137 , -0.52762746,  1.61634633,  0.65964457, -0.42013372,
        0.26192334, -1.50570153, -0.59087528,  0.1989161 , -1.08869193,
        0.12876151, -0.42022222,  2.50608128, -0.51705173, -0.0906612 ,
       -0.26653335, -0.10280874,  1.85216147, -0.47288811,  1.20345952,
        0.08785462])
Drawing sample 310
 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.5646953 , -1.31311378,  0.87194319,  1.17593586,  0.15691624,
        0.78578963, -1.1862952 , -0.24332583, -0.36140433, -1.03216655,
       -0.54137374, -0.72868987,  2.0098474 , -0.81995085,  0.81934511,
       -0.00851914,  0.47648054,  1.25627552, -0.65770019,  0.22501087,
       -0.07570852])
Drawing sample 311
 Accept proportion: 0.985000
 Steps taken: 1000
 array([ 0.09299993, -0.40757973,  1.1132255 ,  1.09008459, -0.31822092,
        0.07342958, -1.62909806,  0.15301521, -0.66801097, -1.09037196,
        0.42457237, -0.34996287,  2.33421092,  0.0667

 Accept proportion: 0.992000
 Steps taken: 1000
 array([-0.58105347, -1.03176404,  0.74091625,  1.24131931, -0.89168417,
        1.24577701, -1.32157033,  0.53523157, -0.10010851, -1.11105453,
       -0.38232837,  0.01253546,  2.82591659, -0.56141452,  0.49720667,
       -0.57864866, -0.02654663,  1.32260636, -0.69230559,  1.45646066,
        0.19665833])
Drawing sample 332
 Accept proportion: 0.991000
 Steps taken: 1000
 array([ 0.13792005,  0.10779284,  0.70781574,  0.4280937 , -1.25489198,
        0.88018614, -0.69129803, -0.72370437, -0.40030976, -1.48174039,
       -0.42541838, -0.3936977 ,  2.39398463, -0.50534573,  0.97433996,
       -0.27132571,  0.01597604,  1.62906842, -1.27536274,  0.55969374,
       -0.3807509 ])
Drawing sample 333
 Accept proportion: 0.994000
 Steps taken: 1000
 array([-8.02915886e-01, -6.75283056e-01,  7.63932588e-01,  3.61205744e-01,
       -7.85380045e-01,  1.39303551e+00, -5.80234035e-01,  1.09947391e-01,
       -9.68994092e-01, -1.13931197e+00, -2.644

 Accept proportion: 0.989000
 Steps taken: 1000
 array([-0.1721988 , -0.93312387,  1.40652934,  0.8939839 , -0.48532346,
        0.67516413, -0.12649014,  0.1377749 ,  0.20736904, -1.56733483,
       -0.12838317, -0.60518283,  1.83973201, -0.07590217,  0.72273833,
       -0.94834184,  0.22040702,  0.948752  , -0.86114006,  0.72283307,
        0.60452853])
Drawing sample 354
 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.79108345, -0.79554757,  0.64800495,  0.73329214, -0.03148108,
        0.36185027, -1.24126738, -0.50076088, -0.84197857, -0.50190394,
        0.44457494, -0.36784298,  1.94334085, -0.21960002,  0.14111248,
        0.01949151,  0.07347234,  1.29106153, -1.14844628,  0.97685035,
       -0.55170501])
Drawing sample 355
 Accept proportion: 0.984000
 Steps taken: 1000
 array([ 0.38000913, -1.06257484,  1.59455886,  1.0202642 ,  0.07719984,
        0.40047232, -0.70004513, -0.16059798,  0.48999411, -0.48811763,
       -0.8574659 , -0.20336683,  1.68235035,  0.1835

 Accept proportion: 0.992000
 Steps taken: 1000
 array([-1.02047932, -0.92488542,  1.18805209,  0.70888412,  0.00878972,
        1.47239265, -1.43251173, -0.26973742, -0.56972466, -0.68255496,
        0.06552717,  0.10921688,  2.13482539, -0.28871266,  0.87201541,
       -0.10923112,  0.1632119 ,  1.29609919, -0.7143918 ,  0.70021794,
        0.34992454])
Drawing sample 376
 Accept proportion: 0.995000
 Steps taken: 1000
 array([-0.4894661 , -0.71787854,  1.01901517,  0.92979239,  0.14276619,
        0.84486229, -1.20472586, -0.46833806, -0.87607557, -1.81050588,
       -0.42921778, -0.59045117,  2.96542516,  0.1181119 ,  1.32478892,
       -0.36484164, -0.08128187,  1.83528687, -0.29147634,  0.15902219,
        0.07794392])
Drawing sample 377
 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 0.42842378, -1.31856002,  1.04992366,  1.06198153,  0.26997682,
        0.41181821, -1.44957865, -0.68646351, -0.10465806, -0.35180127,
        0.50591273,  0.12175947,  2.15704253, -0.9714

 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 0.30835967, -0.51451578,  1.23611109,  0.50636678, -0.00446768,
        0.67831486, -1.24364989, -0.44772684, -0.52532036, -0.84506874,
       -0.29037525, -0.4439802 ,  2.23041139, -0.964106  ,  0.54954568,
       -0.08636347,  0.02917726,  1.3060558 , -0.49227867,  0.60153483,
       -0.0553133 ])
Drawing sample 398
 Accept proportion: 0.985000
 Steps taken: 1000
 array([-0.11171693, -0.70025884,  1.07512829,  0.97733713, -0.56328677,
        1.25848842, -0.43818805, -0.303226  , -0.76235919, -1.17423566,
        0.18534578, -0.01740973,  2.31624361,  0.29500623,  0.41860674,
       -0.11524993, -0.21481833,  0.6599276 , -0.96746571,  0.48147174,
        0.48937447])
Drawing sample 399
 Accept proportion: 0.989000
 Steps taken: 1000
 array([-7.29365264e-04, -1.06849474e+00,  1.00224527e+00,  1.07643636e+00,
       -5.89942266e-01,  1.12643227e+00, -5.54793522e-01,  2.21117609e-01,
       -1.29986036e+00, -1.55785600e+00, -8.134

 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 1.26561591, -0.51575305,  0.68730191,  0.73082307, -0.62643384,
        0.12910373, -0.90938963, -0.78787503,  0.07950346, -0.9779043 ,
       -0.16255863, -0.35591754,  1.70555443, -0.31189939,  0.78658843,
       -0.60794924, -0.06962629,  0.57989631, -0.96432618,  0.8753367 ,
       -0.20122798])
Drawing sample 420
 Accept proportion: 0.983000
 Steps taken: 1000
 array([ 0.28812299, -0.40196679,  0.2950869 ,  0.59096609, -0.30779785,
        1.11197644, -0.63468048, -0.65092863, -0.48844433, -1.34465725,
        0.84019062,  0.10046165,  2.16169474, -0.23542371,  0.5884028 ,
       -0.87294629,  0.00313765,  1.16742121, -0.60797713,  0.95455533,
       -0.00270831])
Drawing sample 421
 Accept proportion: 0.993000
 Steps taken: 1000
 array([ 1.17328222e+00, -1.21752655e+00,  1.00743047e+00,  9.66998192e-01,
       -6.62342694e-01,  8.40344071e-04, -1.33157198e+00, -2.57106449e-01,
       -1.41353586e-01, -1.17262101e+00, -8.353

 Accept proportion: 0.986000
 Steps taken: 1000
 array([ 0.60098897, -1.01708582,  0.8859892 ,  0.19581429, -0.14927899,
        0.79701328, -1.00407495, -0.4871105 , -0.45066563, -0.97950053,
       -0.37965544, -0.0391171 ,  1.44922884, -0.48553341,  0.66633011,
       -0.39731146, -0.47543512,  0.93943914, -1.28219757,  1.1800454 ,
       -0.02124409])
Drawing sample 442
 Accept proportion: 0.996000
 Steps taken: 1000
 array([ 0.33170339, -1.12634428,  1.00253066,  0.39515196,  0.34562757,
        0.35040063, -1.8082392 , -0.29849925, -0.37033795, -0.35816923,
       -0.49873199,  0.9766979 ,  2.31279166, -0.12014993,  1.00290079,
       -1.21994049, -0.28773816,  1.12332434, -0.8561321 ,  0.82061187,
        0.05711788])
Drawing sample 443
 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 0.47210734, -1.1128422 ,  1.42454074,  0.96970695,  0.54769233,
        0.33102568, -1.5899014 , -0.27868024, -1.56765823, -0.75926178,
       -0.11129185, -0.48959076,  2.04761223, -0.5928

 Accept proportion: 0.989000
 Steps taken: 1000
 array([ 0.76696026, -0.91651053,  0.59498397,  0.33365824, -1.01221631,
        0.70421745, -1.85356888,  0.52657286, -0.80434212, -0.92547833,
        0.27117921, -0.70552046,  2.52563192, -0.48698734,  0.76882234,
        0.51185629, -0.20216601,  0.47490532, -0.62476219,  0.98879912,
       -0.21725273])
Drawing sample 464
 Accept proportion: 0.986000
 Steps taken: 1000
 array([-0.55594735, -0.93535496,  0.87072509,  1.09561786,  0.10601122,
        1.16035109, -0.96329227, -0.26914412, -0.14969507, -1.65234894,
        1.05766105, -0.3456062 ,  2.32450498, -0.91350403,  0.59040668,
       -0.71690273, -0.33186721,  1.86316325, -1.40391498,  1.27279249,
        0.34001229])
Drawing sample 465
 Accept proportion: 0.985000
 Steps taken: 1000
 array([ 0.58552472, -0.89445107,  1.06522048,  0.47202816, -0.16754758,
        0.83409451, -0.68545308, -0.27143999, -0.74510439, -1.33531647,
        0.43925336, -0.3976321 ,  1.59485878, -0.5897

 Accept proportion: 0.991000
 Steps taken: 1000
 array([-0.45710302, -0.79373654,  1.42810554,  0.88290093, -0.50108868,
        0.60962934, -0.82399276, -0.38767575,  0.00339786, -0.66436504,
       -0.35814749,  0.14824679,  2.48311411, -0.55589287,  0.97163766,
       -0.04283441,  0.02007162,  1.38140496, -0.58756818,  0.90962466,
       -0.10992635])
Drawing sample 486
 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.16313966, -1.3578918 ,  1.25117844,  0.25168334, -0.33834844,
        0.47230315, -0.63375016,  0.37622308, -0.1760343 , -0.47863171,
       -0.04689783,  0.69641139,  1.60320902,  0.29697885,  0.85339672,
       -0.01675895,  0.03302289,  0.86728002, -1.37867472,  0.28559144,
        0.33476879])
Drawing sample 487
 Accept proportion: 0.987000
 Steps taken: 1000
 array([-0.34181485, -0.88914462,  1.1538432 ,  0.46109598, -0.83393555,
        1.29477929, -1.43256496, -0.26015047, -0.65475577,  0.005015  ,
        0.28602866, -0.13708315,  2.27564554, -0.1225

 Accept proportion: 0.992000
 Steps taken: 1000
 array([ 0.29219071, -1.2868644 ,  0.73293117,  0.47840735, -0.60778926,
        0.868596  , -0.63918545, -0.03381757, -0.50814513, -0.86310702,
       -1.0588036 , -0.37201591,  1.77511262,  0.10831002,  0.49320324,
        0.30823582,  0.61297694,  0.82127915, -0.94472212,  1.06907317,
        0.36793081])
Drawing sample 508
 Accept proportion: 0.982000
 Steps taken: 1000
 array([-0.18496612, -1.10997842,  1.28624487,  0.76671485, -0.14587756,
        0.70082309, -0.50886881, -0.04187824,  0.02910451, -1.19644496,
        0.23964528, -0.76824581,  2.01800954,  0.0277826 ,  0.38013019,
       -0.59888502, -0.08124795,  1.04813919, -0.50849847,  1.2629479 ,
        0.21176792])
Drawing sample 509
 Accept proportion: 0.993000
 Steps taken: 1000
 array([ 0.44291167, -0.89931212,  1.12795788,  0.286058  ,  0.0883405 ,
        0.10319915, -0.82575979, -0.12833301, -0.22729811, -0.61267952,
        0.06158438, -0.92944121,  1.93916387,  0.0035

 Accept proportion: 0.987000
 Steps taken: 1000
 array([ 0.56748802, -0.5198564 ,  1.19018512,  0.83124863, -0.93059145,
        0.94031527, -0.45720631,  0.3465121 , -1.26064926, -1.38219768,
       -0.04851685, -0.08092837,  1.73251036,  0.32161284,  0.44053365,
       -0.80541846,  0.31614118,  1.18175745, -0.72768349,  0.34588797,
       -0.15130048])
Drawing sample 530
 Accept proportion: 0.985000
 Steps taken: 1000
 array([-0.28474224, -0.56335928,  1.087977  ,  0.94400917, -0.04880021,
        0.73981581, -0.76119267,  0.2163253 , -0.61381302, -1.53769371,
        0.41595039,  0.13936192,  1.92430677, -0.01637439,  0.75327084,
       -0.40610456, -0.35957296,  1.863764  , -0.64953617,  0.47316142,
       -0.11913199])
Drawing sample 531
 Accept proportion: 0.990000
 Steps taken: 1000
 array([ 0.24980769, -0.53303502,  1.00596535,  1.03038045, -0.44417907,
        0.86561974, -0.93517674, -0.5719153 , -0.80036548, -1.43145517,
       -0.00446661,  0.56440701,  2.29124399, -0.5376

In [5]:
agents[0].theta

array([ 0.55120043, -0.93110705,  0.50886494,  0.30196138, -0.32998599,
        0.75494717, -0.8012313 , -0.34344166, -1.12135742, -1.43881355,
       -1.51694085, -0.30990006,  2.16531648,  0.69132445,  1.52031972,
       -0.91949164,  0.33560878,  1.32680788, -1.13869   ,  1.174964  ,
       -0.33222766])