In [7]:
import numpy as np
import math

In [47]:

def round_down(val, amt):
    return amt*math.floor(val/amt)

def round_up(val, amt):
    return amt*math.ceil(val/amt)

def intervals(xmin,xmax,spacing):
    return [xmin + spacing*i for i in range(int((xmax-xmin)/spacing)+1)]

def make_hist(a, bin_length):
    a_min = np.min(a)
    a_max = np.max(a)
    # round down bin length
    hist, edges = np.histogram(a, intervals(round_down(a_min, bin_length),
                                round_up(a_max, bin_length),
                                bin_length))
    return hist, edges

def make_hist_from_std_dev(a,factor):
    s = np.std(a)
    bin_length = factor*s
    return make_hist(a, bin_length)

def make_hists(arrs, bin_length):
    a_min = np.min(arrs)
    a_max = np.max(arrs)
    # round down bin length
    li = [np.histogram(a, intervals(round_down(a_min, bin_length),
                                round_up(a_max, bin_length),
                                bin_length)) for a in arrs]
    edges = li[0][1]
    hists = [t[0] for t in li] 
    return hists, edges

def make_hists_from_std_dev(arrs, factor):
    s = np.std(arrs[0])
    bin_length = factor*s
    return make_hists(arrs, bin_length)

def tv(a1,a2):
    return np.sum(np.abs((a1-a2).astype(float)))/np.sum(a1)

#first array is ground truth
def merr(arrs, factor):
    (num_arrs, sample_size, d) = arrs.shape
    tvs = np.zeros((num_arrs-1, d))
    for i in range(d):
        arr_i = arrs[:,:,i]
        hists, edges = make_hists_from_std_dev(arr_i, factor)
        for j in range(num_arrs-1):
            tvs[j,i] = tv(hists[0], hists[j+1])
    merrs = np.sum(tvs, axis=1)/d
    return tvs, merrs
#def ma(true_samples, samples, side_length):
    

In [16]:
"""
    env = LogisticBandit(num_articles, dim, NormalDist(0,1,dim=dim), (NormalDist(0,var,dim=dim)), seed=seed)
    experiment = ExperimentCompare(agents, env, n_steps,
                   seed=seed, verbosity=verbosity)
"""

np.min([1,2,3])

1

In [19]:
#make_hist([-1.2,.4, .9,.95], .5)

make_hist_from_std_dev([np.random.normal() for _ in range(100)], 0.25)

(array([ 1,  1,  0,  1,  1,  8,  4,  4,  4, 10,  9,  9, 11,  7, 10,  7,  4,
         6,  1,  2]),
 array([-2.64346448, -2.40314952, -2.16283457, -1.92251962, -1.68220467,
        -1.44188971, -1.20157476, -0.96125981, -0.72094486, -0.4806299 ,
        -0.24031495,  0.        ,  0.24031495,  0.4806299 ,  0.72094486,
         0.96125981,  1.20157476,  1.44188971,  1.68220467,  1.92251962,
         2.16283457]))

In [42]:
make_hists([[1.5,2.5],[2.5,3.5]], 1)

tv(np.asarray([1,2,3,2,1]),np.asarray([1,3,3,1,1]))

0.2222222222222222

In [48]:
arrs = np.asarray([[[-1,-1],[1,1]],[[-1,-1],[1,-1]],[[1,-1],[1,1]]])
merr(arrs,1)

(array([[0., 1.],
        [1., 0.]]), array([0.5, 0.5]))